// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qTpB8Sxch7zMoJRPO9ARQA-OVVGoFB8',
    appId: '1:661341240935:web:43acdba02e37913b5fdec2',
    messagingSenderId: '661341240935',
    projectId: 'instagram-clone-71e15',
    authDomain: 'instagram-clone-71e15.firebaseapp.com',
    storageBucket: 'instagram-clone-71e15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvSEp1Wv7HmjfkE0ONOkBu_HvcDQsWfeA',
    appId: '1:661341240935:android:50abff34bd208e865fdec2',
    messagingSenderId: '661341240935',
    projectId: 'instagram-clone-71e15',
    storageBucket: 'instagram-clone-71e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRngzNMuUuASWjYSjgJZfjbT08kJn6810',
    appId: '1:661341240935:ios:c2c48ac5ec7161715fdec2',
    messagingSenderId: '661341240935',
    projectId: 'instagram-clone-71e15',
    storageBucket: 'instagram-clone-71e15.firebasestorage.app',
    iosBundleId: 'com.instagramclone.flutter.course.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRngzNMuUuASWjYSjgJZfjbT08kJn6810',
    appId: '1:661341240935:ios:c2c48ac5ec7161715fdec2',
    messagingSenderId: '661341240935',
    projectId: 'instagram-clone-71e15',
    storageBucket: 'instagram-clone-71e15.firebasestorage.app',
    iosBundleId: 'com.instagramclone.flutter.course.flutterCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5qTpB8Sxch7zMoJRPO9ARQA-OVVGoFB8',
    appId: '1:661341240935:web:661bc26726902fba5fdec2',
    messagingSenderId: '661341240935',
    projectId: 'instagram-clone-71e15',
    authDomain: 'instagram-clone-71e15.firebaseapp.com',
    storageBucket: 'instagram-clone-71e15.firebasestorage.app',
  );
}
